---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  chart: cert-manager
  version: 1.14.4
  repo: https://charts.jetstack.io
  targetNamespace: cert-manager
  valuesContent: |-
    # https://github.com/cert-manager/cert-manager/blob/v1.9.1/deploy/charts/cert-manager/values.yaml

    global:
      leaderElection:
        namespace: cert-manager

    installCRDs: true
    replicaCount: 1

    prometheus:
      enabled: false
