---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: haproxy
  namespace: haproxy
  labels:
    app.kubernetes.io/name: haproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy
subjects:
  - kind: ServiceAccount
    name: haproxy
    namespace: haproxy
