---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge
  namespace: homebridge
  labels:
    app.kubernetes.io/name: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
