---
apiVersion: v1
kind: Service
metadata:
  name: metrics-server
  namespace: metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
spec:
  selector:
    app.kubernetes.io/name: metrics-server
  ports:
    - name: https
      port: 443
      targetPort: https
