---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: coredns
  labels:
    app.kubernetes.io/name: coredns
    app.kubernetes.io/component: coredns
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: coredns
      app.kubernetes.io/component: coredns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coredns
        app.kubernetes.io/component: coredns
    spec:
      containers:
        - name: coredns
          image: coredns/coredns:1.11.1
          args:
            - -conf
            - /etc/coredns/Corefile
          ports:
            - name: udp
              containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: coredns
              mountPath: /etc/coredns
      volumes:
        - name: coredns
          configMap:
            name: coredns
