---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
