---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/component: registry
spec:
  selector:
    app.kubernetes.io/name: registry
    app.kubernetes.io/component: registry
  ports:
    - name: registry
      port: 5000
      targetPort: registry
